openapi: 3.0.3
info:
  title: Bathroom Locator API
  description: API documentation for the Bathroom Locator backend
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /bathroom:
    get:
      description: If no bounds, returns list of all bathrooms. If all bounds params, returns bathrooms in bounds.
      parameters:
        - in: query
          name: minLng
          required: false
          schema: { type: number }
        - in: query
          name: minLat
          required: false
          schema: { type: number }
        - in: query
          name: maxLng
          required: false
          schema: { type: number }
        - in: query
          name: maxLat
          required: false
          schema: { type: number }
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 200
            default: 200
          description: Max number of records to return.
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bathroom'
        400:
          description: Invalid parameters
    
    post:
      description: Add a new bathroom
      requestBody:
        description: Details of new bathroom
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBathroom'
      responses:
        201:
          description: Bathroom successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bathroom'

  /bathroom/updates:
    get:
      summary: Get new bathroom updates (long polling)
      description: Returns newly added bathrooms for clients waiting for updates
      responses:
        '200':
          description: Array of new bathrooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bathroom'
  /user/likes:
    get:
      summary: Get a user's liked bathrooms
      parameters:
        - in: query
          name: userId
          schema:
            type: string
          required: true
      responses:
        200:
          description: Successfully got user's liked bathrooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BathroomId'

                  
    post:
      description: Add a like to a bathroom
      requestBody:
        description: User Id and Bathroom Id
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLike'
      responses:
        201:
          description: Like added successfully
        400:
          description: Bad request
    delete:
      description: Unlike a bathroom
      requestBody:
        description: User Id and Bathroom Id
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLike'
      responses:
        200:
          description: Removed like successfully
        404:
          description: Bathroom not found
      
components:
  schemas:
    BathroomBase:
      type: object
      properties:
        name:
          type: string
        position:
          type: object
          properties:
            lat:
              type: number
              format: double
              description: Latitude in decimal degrees
              example: 37.00076576303953
            lng:
              type: number
              format: double
              description: Longitude in decimal degrees
              example: -122.05719563060227
          required:
            - lat
            - lng
        description:
          type: string
        num_stalls:
          type: number
        amenities:
          $ref: '#/components/schemas/Amenities'
        likes:
          type: integer
          default: 0
      required:
        - name
        - position
        - description
        - num_stalls
        - amenities
   
    NewBathroom:
      allOf:
        - $ref: '#/components/schemas/BathroomBase'
      description: "Schema for creating a new bathroom (no id)."

    Bathroom:
      allOf:
        - type: object
          properties:
            id:
              type: string
              format: uuid
          required:
            - id
        - $ref: '#/components/schemas/BathroomBase'
      description: "Full bathroom resource returned by the API."
    
    Amenities:
      type: object
      properties:
        toilet_paper: { type: boolean }
        soap: { type: boolean }
        paper_towel: { type: boolean }
        hand_dryer: { type: boolean }
        menstrual_products: { type: boolean }
        mirror: { type: boolean }
      required:
        - toilet_paper
        - soap
        - paper_towel
        - hand_dryer
        - menstrual_products
        - mirror
  
    UserLike:
      type : object
      properties:
        userId:
          type: string
          format: uuid
        bathroomId:
          type: string
          format: uuid
      required:
        - userId
        - bathroomId

    BathroomId:
      type: string
      format: uuid